// Generated by CoffeeScript 1.10.0
var Tushare, ts;

Tushare = require('./setushare');

ts = new Tushare();

ts.data({
  func: 'get_hist_data',
  args: "'300388',ktype='W'"
}, function(res) {
  return console.log(res);
});

ts.data({
  func: 'get_hist_data',
  args: "'159915',ktype='M'"
}, function(res) {
  return console.log(res);
});

ts.data({
  func: 'get_h_data',
  args: "'300388'"
}, function(res) {
  return console.log(res);
});

ts.done();

//# sourceMappingURL=example.js.map
